schema:
  - https://portal.firmhouse.com/graphql:
      headers:
        X-Project-Access-Token: ${NX_PROJECT_ACCESS_TOKEN}
documents:
  - './src/lib/resources/**/*.graphql'
  - './src/lib/graphql/fragments/*.graphql'
generates:
  src/lib/graphql/generated.ts:
    plugins:
      - typescript
    config:
      skipTypenameForRoot: true
      skipTypename: true
      onlyOperationTypes: true
      flattenGeneratedTypes: true
      strictScalars: true
      scalars:
        ISO8601Date: string
        ISO8601DateTime: string
        JSON: unknown
      avoidOptionals:
        field: true
      extractAllFieldsToTypes: true
  src/:
    preset: 'near-operation-file'
    presetConfig:
      extension: '.generated.ts'
      baseTypesPath: 'lib/graphql/generated.ts'
    plugins:
      - typescript-operations
      - typed-document-node
    config:
      skipTypenameForRoot: true
      skipTypename: true
      onlyOperationTypes: true
      strictScalars: true
      scalars:
        ISO8601Date: string
        ISO8601DateTime: string
        JSON: unknown
      avoidOptionals:
        field: true
      extractAllFieldsToTypes: true
